language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - SYMFONY_VERSION=origin/2.2

before_script:
  - composer install --dev --prefer-source

script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/classification/master/travis

matrix:
  allow_failures:
    - php: hhvm
